name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      id: cache-cargo
      uses: actions/cache@v3
      env:
        cache-name: cache-cargo
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: sudo apt install libatlas-base-dev mesa-vulkan-drivers
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
